In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [6]:
A=pd.DataFrame([[1, 1, 1, 0, 0],[3, 3, 3, 0, 0],[4,4, 4, 0, 0],[5, 5, 5, 0, 0],[0, 2, 0, 4, 4],[0, 0, 0, 5, 5],[0, 1, 0, 2, 2]])

In [7]:
A

0  1  2  3  4
0  1  1  1  0  0
1  3  3  3  0  0
2  4  4  4  0  0
3  5  5  5  0  0
4  0  2  0  4  4
5  0  0  0  5  5
6  0  1  0  2  2

In [12]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=3, n_iter=100, random_state=42)
svd.fit(A)
print(svd.singular_values_)

[12.48101469  9.50861406  1.34555971]


In [13]:
u, s, vh = np.linalg.svd(A, full_matrices=True)

In [40]:
np.set_printoptions(formatter={'float': '{:.2f}'.format})

In [41]:
print(s)

[12.48 9.51 1.35 0.00 0.00]


In [42]:
print(u[:,[0,1,2]])

[[-0.14 0.02 0.01]
 [-0.41 0.07 0.03]
 [-0.55 0.09 0.04]
 [-0.69 0.12 0.05]
 [-0.15 -0.59 -0.65]
 [-0.07 -0.73 0.68]
 [-0.08 -0.30 -0.33]]


In [43]:
vh[[0,1,2],:]

array([[-0.56, -0.59, -0.56, -0.09, -0.09],
       [0.13, -0.03, 0.13, -0.70, -0.70],
       [0.41, -0.80, 0.41, 0.09, 0.09]])

In [54]:
A1= np.dot(np.dot(u[:,[0]],s[0]),vh[[0],:])
print(A1)

[[0.97 1.02 0.97 0.15 0.15]
 [2.90 3.05 2.90 0.46 0.46]
 [3.86 4.07 3.86 0.62 0.62]
 [4.83 5.09 4.83 0.77 0.77]
 [1.07 1.13 1.07 0.17 0.17]
 [0.51 0.53 0.51 0.08 0.08]
 [0.54 0.57 0.54 0.09 0.09]]


In [55]:
A2= np.dot(np.dot(u[:,[1]],s[1]),vh[[1],:])
print(A2)

[[0.03 -0.01 0.03 -0.16 -0.16]
 [0.09 -0.02 0.09 -0.47 -0.47]
 [0.11 -0.03 0.11 -0.62 -0.62]
 [0.14 -0.03 0.14 -0.78 -0.78]
 [-0.71 0.16 -0.71 3.91 3.91]
 [-0.88 0.20 -0.88 4.84 4.84]
 [-0.36 0.08 -0.36 1.95 1.95]]


In [70]:
A3= np.dot(np.dot(u[:,[2]],s[2]),vh[[2],:])
print(A3)

[[0.01 -0.01 0.01 0.00 0.00]
 [0.02 -0.04 0.02 0.00 0.00]
 [0.02 -0.05 0.02 0.01 0.01]
 [0.03 -0.06 0.03 0.01 0.01]
 [-0.36 0.71 -0.36 -0.08 -0.08]
 [0.37 -0.73 0.37 0.08 0.08]
 [-0.18 0.35 -0.18 -0.04 -0.04]]


In [71]:
A-(A1+A2+A3)

0             1             2             3             4
0  2.220446e-16 -2.220446e-16  2.220446e-16 -1.595946e-16 -1.333569e-16
1  0.000000e+00 -8.881784e-16 -4.440892e-16  6.245005e-17  1.682682e-16
2  8.881784e-16  0.000000e+00  4.440892e-16 -4.597017e-17  5.811324e-17
3  0.000000e+00 -8.881784e-16  0.000000e+00  1.379105e-16  2.411266e-16
4 -2.220446e-16 -1.776357e-15  1.221245e-15 -1.776357e-15 -1.776357e-15
5 -3.885781e-16 -5.551115e-16  3.885781e-16 -1.776357e-15 -2.664535e-15
6 -1.110223e-16 -8.881784e-16  6.106227e-16 -8.881784e-16 -8.881784e-16

In [81]:
smat = np.zeros((3, 3), dtype=float)
smat= np.diag(s)

In [82]:
smat

array([[12.48, 0.00, 0.00, 0.00, 0.00],
       [0.00, 9.51, 0.00, 0.00, 0.00],
       [0.00, 0.00, 1.35, 0.00, 0.00],
       [0.00, 0.00, 0.00, 0.00, 0.00],
       [0.00, 0.00, 0.00, 0.00, 0.00]])

In [83]:
X=np.dot(u[:,:3],smat[:3,:3])

In [84]:
Y=np.dot(X,vh[:3,:])

In [85]:
Y

array([[1.00, 1.00, 1.00, 0.00, 0.00],
       [3.00, 3.00, 3.00, -0.00, -0.00],
       [4.00, 4.00, 4.00, 0.00, -0.00],
       [5.00, 5.00, 5.00, -0.00, -0.00],
       [0.00, 2.00, -0.00, 4.00, 4.00],
       [0.00, 0.00, -0.00, 5.00, 5.00],
       [0.00, 1.00, -0.00, 2.00, 2.00]])

In [86]:
np.allclose(A,Y)

True