# Array Manipulations

In [1]:
A = np.random.random((4, 4))
A

NameError: ignored

In [ ]:
A < 0.5

In [ ]:
A[A < 0.5]

### Shape Manipulations

In [ ]:
a = np.random.random(12)
a

In [ ]:
# Create a new Object
A = a.reshape(3, 4)
A

In [ ]:
# Change the object directly
a.shape = (3, 4)
a

In [ ]:
# Convert back to one dimension
a = a.ravel()
a

In [ ]:
A.transpose()

###  Stacking  and splitting Arrays

In [ ]:
A = np.ones((3, 3))
B = np.zeros((3, 3))
np.vstack((A, B))

In [ ]:
np.hstack((A,B))

In [ ]:
np.column_stack((A[:,1],B[:,1]))

In [ ]:
np.row_stack((A[1,:],B[0,:]))

In [ ]:
A = np.arange(16).reshape((4, 4))
A

In [ ]:
[B,C] = np.hsplit(A, 2)
B

In [ ]:
[B,C] = np.vsplit(A, 2)
C

In [ ]:
[A1,A2,A3] = np.split(A,[1,3],axis=1)
A1

In [ ]:
A2

In [ ]:
A3

## Copies or views of objects

In [ ]:
a = np.array([1, 2, 3, 4])
a

In [ ]:
b = a
b

In [ ]:
a[2]=0

In [ ]:
b

In [ ]:
c = a[0:2]
c

In [ ]:
a[0] = 0
c

### For create complete copy, use the copy() function

In [ ]:
c = a.copy()
c
a[0]=5
c


## Friendship Data

In [ ]:
users = [
{ "id": 0, "name": "Hero" },
{ "id": 1, "name": "Dunn" },
{ "id": 2, "name": "Sue" },
{ "id": 3, "name": "Chi" },
{ "id": 4, "name": "Thor" },
{ "id": 5, "name": "Clive" },
{ "id": 6, "name": "Hicks" },
{ "id": 7, "name": "Devin" },
{ "id": 8, "name": "Kate" },
{ "id": 9, "name": "Klein" }
]

In [ ]:
friendship_pairs = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4), (4, 5), (5, 6), (5, 7), (6, 8), (7, 8), (8, 9)]

### Exercise: Visualize this as a graph using Networkx

In [ ]:
# For visualization learn to use Networkx
# Please edit the code below appropriately

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()
G.add_edge(1, 2)
G.add_edge(1, 3)
G.add_edge(1, 5)
G.add_edge(2, 3)
G.add_edge(3, 4)
G.add_edge(4, 5)

# explicitly set positions
pos = {1: (0, 0), 2: (-1, 0.3), 3: (2, 0.17), 4: (4, 0.255), 5: (5, 0.03)}

options = {
    "font_size": 36,
    "node_size": 3000,
    "node_color": "white",
    "edgecolors": "black",
    "linewidths": 5,
    "width": 5,
}
nx.draw_networkx(G, pos, **options)

# Set margins for the axes so that nodes aren't clipped
ax = plt.gca()
ax.margins(0.20)
plt.axis("off")
plt.show()

In [ ]:
# Give colors and labels to the nodes
# https://networkx.org/documentation/latest/auto_examples/drawing/plot_labels_and_colors.html


### Convert this in the form of a matrix with (i,j) being 1 if i is a friend of j else 0

In [ ]:
# Conversion to Dictionary
# Initialize the dict with an empty list for each user id:
friendships = {user["id"]: [] for user in users}
# And loop over the friendship pairs to populate it:
for i, j in friendship_pairs:
    friendships[i].append(j) # Add j as a friend of user i
    friendships[j].append(i) # Add i as a friend of user j

### “What’s the average number of connections?”

In [ ]:
def number_of_friends(user):
    # Complete this function
    

In [ ]:
# Compact way of computing the sum of friends for all users
total_connections = sum(number_of_friends(user)
                        for user in users) # 24

In [ ]:
# Compute the average
num_users =          # length of the users list
avg_connections =    # 24 / 10 == 2.4

In [ ]:
# Who are the most connected people (with most number of friends?)

# Create a list (user_id, number_of_friends).
num_friends_by_id =

In [ ]:
num_friends_by_id.sort( # Sort the list
key=lambda id_and_friends: id_and_friends[1], # by num_friends
reverse=True) # largest to smallest

### Friends of Friends

In [ ]:
# What is wrong with this function??

def foaf_ids_bad(user):
    """foaf is short for "friend of a friend" """
    return [foaf_id
    for friend_id in friendships[user["id"]]
    for foaf_id in friendships[friend_id]]

In [ ]:
# Can you write a better function to find friends of friends?
# can your function also tell us how many different ways someone is a friend of friend?




### Interests of people

In [ ]:
interests = [
(0, "Hadoop"), (0, "Big Data"), (0, "HBase"), (0, "Java"),
(0, "Spark"), (0, "Storm"), (0, "Cassandra"),
(1, "NoSQL"), (1, "MongoDB"), (1, "Cassandra"), (1, "HBase"),
(1, "Postgres"), (2, "Python"), (2, "scikit-learn"), (2, "scipy"),
(2, "numpy"), (2, "statsmodels"), (2, "pandas"), (3, "R"), (3, "Python"),
(3, "statistics"), (3, "regression"), (3, "probability"),
(4, "machine learning"), (4, "regression"), (4, "decision trees"),
(4, "libsvm"), (5, "Python"), (5, "R"), (5, "Java"), (5, "C++"),
(5, "Haskell"), (5, "programming languages"), (6, "statistics"),
(6, "probability"), (6, "mathematics"), (6, "theory"),
(7, "machine learning"), (7, "scikit-learn"), (7, "Mahout"),
(7, "neural networks"), (8, "neural networks"), (8, "deep learning"),
(8, "Big Data"), (8, "artificial intelligence"), (9, "Hadoop"),
(9, "Java"), (9, "MapReduce"), (9, "Big Data")
]

In [ ]:
# Can you write functions to find people with similar interests?
# Who shares most interests with each other?
# Are they friends or friends or friends?

# Scipy Sparse Matrices

In [ ]:
from scipy import sparse
import numpy as np

In [ ]:
# Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)
print("NumPy array:\n{}".format(eye))

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Convert the NumPy array to a SciPy sparse matrix in CSR format
# Only the nonzero entries are stored
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [ ]:
# Converting to sparse representations
# More details on : http://www.scipy-lectures.org/
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO representation:\n{}".format(eye_coo))

COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


# Vectorized Operations

In [ ]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.3 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
% Vectorized Operations

print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


Computations using vectorization through ufuncs are nearly always more efficient than their counterpart
implemented through Python loops, especially as the arrays grow in size. Any time you see such a loop
in a Python script, you should consider whether it can be replaced with a vectorized expression.

In [ ]:
%timeit (1.0 / big_array)

3.54 ms ± 271 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#  Trigonometric Functions